# Generated by Django 4.1.5 on 2023-11-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('change_value', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trade_date', models.DateTimeField()),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.currencypair')),
            ],
        ),
    ]
