# Generated by Django 4.1.5 on 2023-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_trade_currency_pair_delete_currencypair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='currency_pair',
            field=models.CharField(choices=[('EURCAD', 'EURCAD'), ('USDJPY', 'USDJPY'), ('GBPUSD', 'GBPUSD'), ('EURUSD', 'EURUSD')], max_length=10),
        ),
    ]
